### ISSUE TITLE
[Video Player] Support gstreamer dmabuf in video_player

### ISSUE THREAD

**Issue by makotosato-at** [sony/flutter-elinux-plugins#64]
Hello.
I have i.MX8MP board and using video_player.
This SoC has a VPU(Video Proccessing Unit) so that it can hardware decode H.264 with gstreamer.
But, 1080p 30fps or 60fps video, the following _gst_buffer_extract()_ is the bottleneck and playback is slow.
(_gst_extract_buffer()_ takes about 60ms.)
gst_video_player.cc:
```
const uint8_t* GstVideoPlayer::GetFrameBuffer() {
  std::shared_lock<std::shared_mutex> lock(mutex_buffer_);
  if (!gst_.buffer) {
    return nullptr;
  }

  const uint32_t pixel_bytes = width_ * height_ * 4;
  gst_buffer_extract(gst_.buffer, 0, pixels_.get(), pixel_bytes);
  return reinterpret_cast<const uint8_t*>(pixels_.get());
}
```
I think the availability of **dmabuf** would solve this problem.
Are there any plans to support gstreamer **dmabuf** in video_player?
(In my environment, _gst_is_dmabuf_memory()_ returns TRUE, so I can use **dmabuf**.)

**Comment by Kofhein** [comment]
@makotosato-at , you may try to set qos to TRUE, for me it improved playback and also resolved issue with disappearing sound. But for sure 60ms bottleneck is problem that should be solved.

**Comment by makotosato-at** [comment]
@Kofhein Thank you for the information.  I tried that, but it didn't solve the problem...

@HidenoriMatsubayashi Sorry, I don't have any patches...

**Comment by Kofhein** [comment]
@makotosato-at , my comment might be helpful to you too https://github.com/sony/flutter-elinux-plugins/issues/63#issuecomment-1399358789 I've resolved similar issue, but in my case I've got desktop HW, so in my case gst_buffer_extract wasn't bottleneck.
Also I've seen dma buf based implementation here https://github.com/ardera/flutter-pi/blob/master/src/plugins/gstreamer_video_player/player.c , but it's C based solution for RasbPi and seems there GPU textures already implemented. In most cases I've seen this kind of dmabuf implementation it was connected to GPU texture using Frame buffer and rendering buffer with planes.

**Comment by KamisiT** [comment]
I have a s905w and I have been trying to use hardware decoding (v4l2m2m) in conjuction with gstreamer.  The OS running on the s905w is custom built using buildroot however, some plugins like v4l2convert  is missing. The plan is to run a flutter application built with elinux on the box, and run HlS. I'd appreciate guidance on this
